# Generated by Django 2.0.1 on 2018-01-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='content',
        ),
    ]
